# Generated by Django 4.0.6 on 2022-11-13 17:51

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Abids Tutorials', max_length=100)),
                ('about_title', models.CharField(default='Abids Tutorials', max_length=100)),
                ('about_us', models.TextField(blank=True, max_length=500, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=80, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=80, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('lecture_note', models.FileField(blank=True, null=True, upload_to='notes/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='photos/courses/')),
                ('course_price', models.IntegerField(default=0)),
                ('released', models.BooleanField(default=False)),
                ('course_feature_1', models.CharField(blank=True, max_length=100, null=True)),
                ('course_feature_2', models.CharField(blank=True, max_length=100, null=True)),
                ('course_feature_3', models.CharField(blank=True, max_length=100, null=True)),
                ('catchy_intro', models.CharField(default='Catchy Intro', max_length=100)),
                ('catchy_description', models.CharField(blank=True, max_length=500, null=True)),
                ('instructor_name', models.CharField(default='Abiduzzaman Abid', max_length=80)),
                ('enrolled_students', models.IntegerField(default=0)),
                ('number_of_classes', models.IntegerField(default=0)),
                ('total_video_duration', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('video_description', models.TextField(blank=True, max_length=500, null=True)),
                ('video_url', models.CharField(blank=True, max_length=150, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=course.models.get_file_path)),
                ('video_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('unit_price', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('manually_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='IncludedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.unit'),
        ),
    ]
