# Generated by Django 4.0.6 on 2022-07-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('lecture_note', models.FileField(blank=True, null=True, upload_to='notes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='cat_image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/courses/'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('video_description', models.TextField(blank=True, max_length=500, null=True)),
                ('video_url', models.CharField(max_length=150)),
                ('video_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.unit'),
        ),
    ]
