# Generated by Django 4.0.6 on 2022-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_price_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
