# Generated by Django 4.0.6 on 2022-07-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_feature_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_feature_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_feature_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
