# Generated by Django 4.0.6 on 2022-07-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catchy_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='catchy_intro',
            field=models.CharField(default='Catchy Intro', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Abiduzzaman Abid', max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_video_duration',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.CreateModel(
            name='Learning_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Included_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
