# Generated by Django 4.0.6 on 2022-07-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_catchy_description_course_catchy_intro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Included_point',
            new_name='IncludedPoint',
        ),
        migrations.RenameModel(
            old_name='Learning_point',
            new_name='LearningPoint',
        ),
    ]
