# Generated by Django 4.0.6 on 2022-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_included_point_includedpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
