# Generated by Django 4.0.6 on 2022-10-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_transaction'),
        ('course', '0011_subscription_subscription_type_subscription_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='manually_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
