# Generated by Django 4.0.6 on 2022-10-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='website_name',
            field=models.CharField(default='Abids Tutorials', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(default='Abids Tutorials', max_length=100),
        ),
    ]
