# Generated by Django 4.0.6 on 2022-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_about_website_name_alter_about_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
