# Generated by Django 4.0.6 on 2022-10-28 11:19

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_video_video_file_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=course.models.get_file_path),
        ),
    ]
