# Generated by Django 4.0.6 on 2022-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(blank=True, max_length=15, null=True)),
                ('rocket_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
