# Generated by Django 4.0.6 on 2022-11-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(blank=True, max_length=15, null=True)),
                ('rocket_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.CharField(default=0, max_length=20)),
                ('status', models.CharField(choices=[('P', 'Processing'), ('R', 'Rejected'), ('A', 'Approved'), ('D', 'Dismissed')], default='P', max_length=20)),
                ('comment_for_user', models.TextField(blank=True, default='Your Payment is processing, please wait for us to update the received amount.', max_length=250, null=True)),
                ('date_placed', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(blank=True, max_length=15, null=True)),
                ('trxID', models.CharField(blank=True, max_length=25, null=True)),
                ('sent_amount', models.CharField(default=0, max_length=20)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order')),
            ],
        ),
    ]
