# Generated by Django 4.0.6 on 2022-10-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sent_amount',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
