# Generated by Django 4.0.6 on 2022-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_sent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
