# Generated by Django 4.0.6 on 2022-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='institute',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
